# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/PredictiveMaintenance2',
                'doc_host': 'https://lalithapavani-b.github.io',
                'git_url': 'https://github.com/lalithapavani-b/PredictiveMaintenance2',
                'lib_path': 'PredictiveMaintenance2'},
  'syms': { 'PredictiveMaintenance2.Datasets': { 'PredictiveMaintenance2.Datasets.explore_dataset': ( 'datasets.html#explore_dataset',
                                                                                                      'PredictiveMaintenance2/Datasets.py'),
                                                 'PredictiveMaintenance2.Datasets.load_dataset': ( 'datasets.html#load_dataset',
                                                                                                   'PredictiveMaintenance2/Datasets.py')},
            'PredictiveMaintenance2.Visualize': { 'PredictiveMaintenance2.Visualize.plot': ( 'visualize.html#plot',
                                                                                             'PredictiveMaintenance2/Visualize.py')},
            'PredictiveMaintenance2.core': { 'PredictiveMaintenance2.core.foo': ('core.html#foo', 'PredictiveMaintenance2/core.py'),
                                             'PredictiveMaintenance2.core.greet': ('core.html#greet', 'PredictiveMaintenance2/core.py')},
            'PredictiveMaintenance2.utils': {}}}
