# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_Introduction.ipynb.

# %% auto 0
__all__ = ['data', 'foo']

# %% ../nbs/00_Introduction.ipynb 8
data = pd.read_csv('predictive_maintenance_dataset.csv')

# %% ../nbs/00_Introduction.ipynb 9
def foo(): pass
